### ISSUE TITLE
Please add your code that you used to find your answers.

### ISSUE THREAD

**Issue by 22f3001377** [ak5h1ta/tds-project1#1]
**It has been mentioned that you need to upload your code for the sake of peer review. I urge you to upload your code for a fair review. Thank you.**

**Comment by ak5h1ta** [comment]
> **It has been mentioned that you need to upload your code for the sake of peer review. I urge you to upload your code for a fair review. Thank you.**

Sorry for the inconvenience, I just added it!

**Comment by 22f3001377** [comment]
That wasn't an inconvenience at all! They added the requirement for the
evaluation later on 🥲 Thank you for listening to my request.
